name: trash_cash
description: "A waste-to-wealth digital marketplace for Cameroon"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
  
    sdk: flutter

  provider: ^6.1.1

  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_database: ^12.1.2
  firebase_messaging: ^16.1.1
  firebase_storage: ^13.0.6

  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^7.1.0

  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0


  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2

  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0

  intl: any

  image_picker: ^1.0.5

  flutter_local_notifications: ^19.5.0

  url_launcher: ^6.2.2
  share_plus: ^12.0.1

  animate_do: ^4.2.0
  smooth_page_indicator: ^2.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  
    
  generate: true

  uses-material-design: true
